######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 19 04:18:29 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += ". src"
INCLUDEPATH += . src

# Input
HEADERS += src/backpropagation.h \
           src/BadPathEx.h \
           src/exception.h \
           src/ImageFeeder.h \
           src/ImagePreparer.h \
           src/layer.h \
           src/mainscreen.h \
           src/network.h \
           src/network_interface.h \
           src/neuron.h \
           src/NullParamEx.h \
           src/qxmlpersistance.h \
 	   src/networkeditor.h
FORMS += src/gui.ui \
 	 src/networkeditor.ui
SOURCES += src/backpropagation.cpp \
           src/BadPathEx.cpp \
           src/exception.cpp \
           src/ImageFeeder.cpp \
           src/ImagePreparer.cpp \
           src/layer.cpp \
           src/main.cpp \
           src/mainscreen.cpp \
           src/network.cpp \
           src/neuron.cpp \
           src/NullParamEx.cpp \
           src/qxmlpersistance.cpp \
 	   src/networkeditor.cpp
QT += xml

